### ISSUE TITLE
Running mypy with reviewdog has no output

### ISSUE THREAD

**Issue by vnmabus** [tsuyoshicho/action-mypy#111]
I am trying to use your action in another project, but I have problems making it work:
- First, if an error occurs during the action setup (installation, install_types, etc), the action happily returns an ok status and does nothing.
- Second, the step "Running mypy with reviewdog 🐶 ..." shows no output and passes without errors, even when there are typing errors in the project:
    - https://github.com/vnmabus/rdata/actions/runs/7628880846/job/20780993774

**Comment by tsuyoshicho** [comment]
Answer will be a little late

**Comment by vnmabus** [comment]
I solved 2 (it was caused by misconfiguration, but I still think that errors should be reported). Problem 1 remains, though.

**Comment by tsuyoshicho** [comment]
@vnmabus 
I'm glad it was resolved.

Regard

**Comment by tsuyoshicho** [comment]
Consider this issue.

> First, if an error occurs during the action setup (installation, install_types, etc), the action happily returns an ok status and does nothing.

**Comment by tsuyoshicho** [comment]
Hi @vnmabus 

Issue and will proceed to respond to the issue.

Thank you for your report.
As for this Issue, we will close it for now.
