### ISSUE TITLE
"Running mypy with reviewdog 🐶 ..." does not comment and shows no error, despite errors.

### ISSUE THREAD

**Issue by bernhardkaindl** [tsuyoshicho/action-mypy#115]
I run into the same issue as the 2nd issue reported in #111:

> Second, the step "Running mypy with reviewdog 🐶 ..." shows no output and passes without errors, even when there are typing errors in the project: 

I enabled mypy --verbose and see that mypy is issuing two warnings for a file (it mentions two times that it has a warning about a place in the file), in the step "Running mypy with reviewdog 🐶 ...", but the action hides the actual errors and does not add a comment to the PR.

**Comment by bernhardkaindl** [comment]
Example PR: https://github.com/xenserver-next/xen-api/pull/6
Workflow output: https://github.com/xenserver-next/xen-api/actions/runs/7688914348/job/20950684779?pr=6

I am still trying to diagnose it.

**Comment by tsuyoshicho** [comment]
Hi @bernhardkaindl 

Thank you

Wait a little longer

**Comment by tsuyoshicho** [comment]
Hi @bernhardkaindl 

https://github.com/xenserver-next/xen-api/actions/runs/7688914348/job/20950684779?pr=6
https://github.com/tsuyoshicho/action-mypy/issues/38
mypy may return multi-line results.
Cannot be improved until a solution is created, such as being able to get results in JSON!

This can be mitigated somewhat with `ignore_note`.

Your PR is helpful, I will examine it and merge it.

**Comment by tsuyoshicho** [comment]
Hi @bernhardkaindl 

I have released v4.0.1.
Please try to understand and use the above support.

https://github.com/tsuyoshicho/action-mypy/releases/tag/v4.0.1

This issue is closed.
