### ISSUE TITLE
Allow specifying a mypy version

### ISSUE THREAD

**Issue by justinchuby** [tsuyoshicho/action-mypy#48]
It would be very useful to be able to specify a mypy version since some projects may be running on old versions of mypy

**Comment by justinchuby** [comment]
Thanks! I wasn’t aware of this option. Which file should I specify the version in?

**Comment by justinchuby** [comment]
From the script it seems if I have mypy in the environment it will just use that. Is that correct?

**Comment by tsuyoshicho** [comment]
@justinchuby 
I reconsidered.

Basically, the reviewdog action's modus operandi(other actions) is "the project's files are installed, and we test it".

In "action-mypy", added a follow that the latest is installed even if it is not installed by not defining the project.

I would like you to use the follow of a specific version by including the one managed by the project.
(the older version of the project have the older definition)

We decided not to include the ability to specify a specific version (further follow).

Thanks for your report.
