### ISSUE TITLE
Feature request: Multiple targets for mypy

### ISSUE THREAD

**Issue by mnschmit** [tsuyoshicho/action-mypy#86]
Hi @tsuyoshicho, first of all, thank you for this very useful action!

I had a little problem using it in my GitHub workflow because it only supports a single target at the moment. I tried putting multiple files separated by white space in the target input of the action (like `file1` `file2`), but I saw that [this line](https://github.com/tsuyoshicho/action-mypy/blob/0ee5a555db563979f4a8acf51a493b1ad39febcf/script.sh#L62) quotes the target and therefore `mypy` looks for a single file (or directory) with the name `file1 file2`, i.e., containing the white space.

The context of why I'd like to do this is that I identify the changed or added files in a pull request using the GitHub action `dorny/paths-filter`. It supports outputting all changed files in a shell-like list, i.e., with white space as delimiter. I'd like `mypy` to only lint the changed/added files and not the whole repository because linting issues that weren't introduced by the current PR shouldn't block it from being merged.
As a workaround, I tried setting `target` to `""` and putting the list of files in the mypy flags input. Unfortunately, that doesn't work either because then the default value of `"."` is inserted in the same line I linked above.

Do you think your action could support this use case?

**Comment by tsuyoshicho** [comment]
I'll think about it. Please wait a while.

**Comment by tsuyoshicho** [comment]
@mnschmit 
#87 and #89 for Update target: support multi targets.

So please use next release v3.13.0.

**Comment by mnschmit** [comment]
Great, thank you!
